# Generated by Django 3.2.9 on 2021-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Enemy', 'Enemy'), ('Weapon', 'Weapon'), ('Hero', 'Hero')], default='Enemy', max_length=10)),
                ('base_hp', models.IntegerField(default=5)),
                ('base_attack', models.IntegerField(default=5)),
                ('base_defense', models.IntegerField(default=5)),
                ('base_speed', models.IntegerField(default=5)),
                ('image', models.ImageField(upload_to='')),
                ('paid', models.BooleanField(default=False)),
                ('min_level', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
            ],
            options={
                'verbose_name_plural': 'Codex',
            },
        ),
    ]
